
version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: chat_app_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3307:3306"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
  #   container_name: chat_app_elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms4g -Xmx4g
  #   ports:
  #     - "9200:9200"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3



  redis:
    image: redis:latest
    container_name: chat_app_redis
    # ports:
    #   - "6379:6379"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
    volumes:
      - .:/code
      - ./tmp/pids:/tmp/pids
      - ./tmp/cache:/tmp/cache
      - ./log:/log
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    working_dir: /rails
